'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const source = fs.readFileSync(path.join(__dirname, '../apps/launcher/launcher-ui.js'), 'utf8');
const launcherCss = fs.readFileSync(path.join(__dirname, '../apps/launcher/launcher.css'), 'utf8');
function extract(name, next) { return source.slice(source.indexOf('    function ' + name + '('), source.indexOf('    function ' + next + '(')); }
const rows = [{}, {}, {}];
let candidate;
const root = {contains(node) {return node === candidate;}, querySelectorAll() {return rows;}};
const document = {activeElement:null};
const context = {root, document};
vm.runInNewContext(extract('hasUsableFocus', 'activeScope') + extract('belongsAtPageTop', 'focusNode'), context);
candidate = {closest() {return null;}, getBoundingClientRect() {throw new Error('Startup must not force layout');}};
document.activeElement = candidate;
assert.strictEqual(context.hasUsableFocus(), true);
candidate.disabled = true;
assert.strictEqual(context.hasUsableFocus(), false);
candidate.disabled = false;
candidate.closest = () => ({});
assert.strictEqual(context.hasUsableFocus(), false, 'hidden dialogs cannot retain focus');
document.activeElement = {};
assert.strictEqual(context.hasUsableFocus(), false);
candidate.closest = () => null;
assert.strictEqual(context.belongsAtPageTop(candidate, rows[0]), true);
assert.strictEqual(context.belongsAtPageTop(candidate, rows[1]), true);
assert.strictEqual(context.belongsAtPageTop(candidate, rows[2]), false);
assert.ok(/function directPresetMjpeg\(preset\)/.test(source), 'focused camera preview must have a direct MJPEG helper');
assert.ok(/var sources = \[\s*String\(preset && preset\.content/.test(source), 'camera preset content must win over profile-derived preview URL');
assert.ok(/button\.addEventListener\('focus'[\s\S]*?}, 1000\);/.test(source), 'camera MJPEG promotion must wait one second of stable focus');
assert.ok(/className = 'launcher-camera-live'/.test(source), 'focused camera MJPEG must use a separate live image layer');
assert.ok(/className = 'launcher-camera-live-badge'/.test(source) && !/liveBadge\.hidden = true/.test(source), 'camera LIVE badge must appear as soon as live mode starts');
assert.ok(/button\.addEventListener\('blur'[\s\S]*?stopActiveLivePreview\(\)/.test(source), 'camera MJPEG live layer must stop on blur');
assert.ok(/\.launcher-camera-live\{[^}]*position:absolute!important[^}]*z-index:3!important/.test(launcherCss), 'camera MJPEG live layer must be above the cached snapshot');
assert.ok(/\.launcher-camera-live-badge\{[^}]*right:8px[^}]*bottom:8px/.test(launcherCss), 'camera LIVE badge must sit at the bottom-right of the preview');
assert.ok(/\.launcher-boot-cover\[hidden\]\{display:none!important\}/.test(launcherCss), 'hidden loading cover must never remain visually displayed');
assert.ok(/\.launcher-motion-disabled \.launcher-boot-cover:not\(\[hidden\]\) \.launcher-boot-mark i\{animation:launcher-boot-pulse[^}]*!important\}/.test(launcherCss), 'visible loading cover must stay animated even when launcher motion is disabled');
console.log('launcher startup focus tests: PASS');
